"""add user_weather_preferences model

Revision ID: d1468ca8a847
Revises: 19e5dc2aa277
Create Date: 2024-04-17 20:19:13.366046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1468ca8a847'
down_revision: Union[str, None] = '19e5dc2aa277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_weather_preferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('temp_min', sa.Integer(), nullable=True),
    sa.Column('temp_max', sa.Integer(), nullable=True),
    sa.Column('likes_rain', sa.Boolean(), nullable=True),
    sa.Column('likes_sun', sa.Boolean(), nullable=True),
    sa.Column('likes_wind', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_weather_preferences')
    # ### end Alembic commands ###
