"""new fields for user_weather_preferences

Revision ID: f0a424e61977
Revises: d1468ca8a847
Create Date: 2024-04-18 19:27:10.568313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0a424e61977'
down_revision: Union[str, None] = 'd1468ca8a847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_weather_preferences', sa.Column('likes_fog', sa.Boolean(), nullable=True))
    op.add_column('user_weather_preferences', sa.Column('likes_snow', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_weather_preferences', 'likes_snow')
    op.drop_column('user_weather_preferences', 'likes_fog')
    # ### end Alembic commands ###
